export type BibleWordHint = {
  clue: string;
  reference?: string;
};

// These clues are deliberately phrased without the answer. References are
// supporting reading, not necessarily direct quotations of the clue.
export const BIBLE_WORD_HINTS: Record<string, BibleWordHint> = {
  // Bible books
  GENESIS: { clue: "The Bible book that begins with creation and follows the first families of faith.", reference: "Genesis 1:1" },
  EXODUS: { clue: "The Bible book about Israel leaving Egypt under Moses' leadership.", reference: "Exodus 12:31–42" },
  LEVITICUS: { clue: "A book of laws about worship, holiness, priests, and sacrifices." },
  NUMBERS: { clue: "The wilderness book named for two censuses of the Israelites." },
  DEUTERONOMY: { clue: "Moses' final speeches restating God's law before Israel enters Canaan." },
  JOSHUA: { clue: "The book describing Israel's entrance into the Promised Land after Moses." },
  JUDGES: { clue: "A book about Israel's repeated cycle of rebellion, oppression, and rescue." },
  RUTH: { clue: "A short book about loyalty, redemption, and a Moabite widow in Bethlehem." },
  SAMUEL: { clue: "These books trace Israel's transition from judges to kings, including Saul and David." },
  KINGS: { clue: "These books recount Israel's monarchy from Solomon through division and exile." },
  CHRONICLES: { clue: "These books retell Israel's history with special attention to David, the temple, and worship." },
  EZRA: { clue: "A post-exile book about returning to Jerusalem and rebuilding the temple." },
  NEHEMIAH: { clue: "A book about rebuilding Jerusalem's walls despite determined opposition." },
  ESTHER: { clue: "A book about a Jewish queen who courageously intervenes to save her people." },
  PSALMS: { clue: "The Bible's collection of songs and prayers for worship, sorrow, gratitude, and praise." },
  PROVERBS: { clue: "A wisdom book filled with concise instruction for godly daily living." },
  ECCLESIASTES: { clue: "A wisdom book examining life's meaning and the limits of earthly pursuits." },
  ISAIAH: { clue: "A prophetic book of judgment and hope that foretells a suffering servant." },
  JEREMIAH: { clue: "The prophetic book of a weeping messenger who warned Jerusalem before exile." },
  LAMENTATIONS: { clue: "Five poetic laments grieving the fall and destruction of Jerusalem." },
  EZEKIEL: { clue: "A prophetic book known for vivid visions, a valley of dry bones, and promised restoration." },
  DANIEL: { clue: "A book combining stories from Babylonian exile with visions of kingdoms and God's rule." },
  HOSEA: { clue: "A prophetic book whose troubled marriage portrays God's faithful love for unfaithful Israel." },
  JOEL: { clue: "A prophetic book that uses a locust invasion to announce the day of the Lord." },
  AMOS: { clue: "A shepherd-prophet's book calling Israel to justice and genuine worship." },
  OBADIAH: { clue: "The shortest Old Testament book, announcing judgment against Edom." },
  JONAH: { clue: "A prophetic book about a reluctant messenger sent to Nineveh." },
  MICAH: { clue: "A prophetic book calling people to act justly, love mercy, and walk humbly with God." },
  NAHUM: { clue: "A prophetic book announcing the fall of Nineveh, capital of Assyria." },
  HABAKKUK: { clue: "A prophet questions injustice and learns that the righteous live by faith." },
  ZEPHANIAH: { clue: "A prophetic book warning of the day of the Lord and promising restoration." },
  HAGGAI: { clue: "A prophet urges returned exiles to stop delaying and rebuild God's temple." },
  ZECHARIAH: { clue: "A post-exile prophetic book filled with night visions and messianic hope." },
  MALACHI: { clue: "The final Old Testament book confronts careless worship and promises a coming messenger." },
  MATTHEW: { clue: "A Gospel presenting Jesus as the promised King and recording the Sermon on the Mount." },
  MARK: { clue: "The shortest Gospel, moving quickly through the actions and suffering of Jesus." },
  LUKE: { clue: "A carefully researched Gospel emphasizing compassion, prayer, and good news for all people." },
  JOHN: { clue: "A Gospel organized around signs and declarations revealing Jesus' identity." },
  ACTS: { clue: "The New Testament history of the Holy Spirit empowering the early church's mission." },
  ROMANS: { clue: "Paul's detailed letter explaining sin, grace, faith, and new life in Christ." },
  CORINTHIANS: { clue: "Paul's letters addressing division, worship, love, resurrection, and generosity in a Greek church." },
  GALATIANS: { clue: "Paul's letter defending justification by faith and freedom from reliance on the law." },
  EPHESIANS: { clue: "Paul's letter about unity in Christ, the church, and the armor of God." },
  PHILIPPIANS: { clue: "A joyful prison letter urging believers to imitate Christ's humility." },
  COLOSSIANS: { clue: "Paul's letter emphasizing the supremacy and sufficiency of Christ." },
  THESSALONIANS: { clue: "Paul's letters encouraging a young church about holy living and Christ's return." },
  TIMOTHY: { clue: "Paul's pastoral letters to a younger ministry leader in Ephesus." },
  TITUS: { clue: "A pastoral letter about appointing elders and teaching healthy Christian living in Crete." },
  PHILEMON: { clue: "Paul's brief personal appeal for a runaway servant to be welcomed as a brother." },
  HEBREWS: { clue: "A New Testament book showing Christ as greater than angels, Moses, and the old covenant priesthood." },
  JAMES: { clue: "A practical letter teaching that genuine faith is demonstrated through action." },
  PETER: { clue: "Letters encouraging suffering believers to remain holy, hopeful, and alert." },
  JUDE: { clue: "A short letter urging believers to contend for the faith against corrupt teachers." },
  REVELATION: { clue: "The Bible's final book, filled with visions of judgment, victory, and renewed creation." },

  // Bible people
  ADAM: { clue: "The first man, formed from the dust and placed in Eden." },
  ABEL: { clue: "The shepherd whose acceptable offering provoked his brother's jealousy." },
  CAIN: { clue: "The farmer who murdered his younger brother after God rejected his offering." },
  SETH: { clue: "The son born to the first couple after the death of Abel." },
  ENOCH: { clue: "A man who walked faithfully with God and was taken away without a recorded death." },
  NOAH: { clue: "The righteous man who built an ark before the great flood." },
  SHEM: { clue: "A son of the ark-builder and ancestor in Abraham's family line." },
  JAPHETH: { clue: "One of the three sons who entered the ark with their father." },
  ABRAHAM: { clue: "The patriarch called to leave his homeland and promised descendants as numerous as the stars." },
  SARAH: { clue: "The patriarch's wife who gave birth to the promised son in old age." },
  HAGAR: { clue: "An Egyptian servant who met the God who sees in the wilderness." },
  ISAAC: { clue: "The promised son of an elderly couple who was nearly offered on Mount Moriah." },
  REBEKAH: { clue: "The woman who offered water to a traveler and his camels before becoming a patriarch's wife." },
  ESAU: { clue: "The hairy elder twin who traded his birthright for a meal." },
  JACOB: { clue: "The younger twin renamed Israel after wrestling through the night." },
  LEAH: { clue: "The elder sister and first wife of Jacob, mother of six of his sons." },
  RACHEL: { clue: "The beloved wife for whom Jacob worked many years and mother of Joseph and Benjamin." },
  JOSEPH: { clue: "The dreamer sold by his brothers who later governed Egypt and preserved his family." },
  BENJAMIN: { clue: "The youngest son of Jacob and full brother of Joseph." },
  MOSES: { clue: "The leader called from a burning bush to bring Israel out of Egypt." },
  AARON: { clue: "Moses' brother, spokesman, and Israel's first high priest." },
  MIRIAM: { clue: "The prophetess and sister of Moses who led women in song after crossing the sea." },
  CALEB: { clue: "One of two faithful spies who believed Israel could enter the Promised Land." },
  RAHAB: { clue: "The woman in Jericho who hid Israelite spies and marked her house with a scarlet cord." },
  DEBORAH: { clue: "A prophetess and judge who summoned Barak to lead Israel against Sisera." },
  BARAK: { clue: "The military commander who went into battle after a prophetess agreed to accompany him." },
  GIDEON: { clue: "The reluctant judge who defeated a vast army with only three hundred men." },
  ABIMELECH: { clue: "Gideon's son who made himself king after killing most of his brothers." },
  JEPHTHAH: { clue: "The rejected warrior who became a judge and made a tragic vow." },
  SAMSON: { clue: "The exceptionally strong judge whose uncut hair was connected to his Nazirite vow." },
  DELILAH: { clue: "The woman who repeatedly pressed a judge to reveal the secret of his strength." },
  NAOMI: { clue: "The bereaved mother-in-law who returned from Moab to Bethlehem with a loyal companion." },
  BOAZ: { clue: "The generous Bethlehem landowner who served as a family redeemer." },
  HANNAH: { clue: "The woman who prayed for a child and dedicated her son to serve at the sanctuary." },
  SAUL: { clue: "Israel's first king, from the tribe of Benjamin, whose disobedience cost him the throne." },
  JONATHAN: { clue: "The king's son whose covenant friendship with David survived his father's hostility." },
  DAVID: { clue: "A shepherd who became king and was known as a man after God's heart.", reference: "1 Samuel 13:14; Acts 13:22" },
  ABSALOM: { clue: "David's handsome son who rebelled, seized Jerusalem, and died caught in a tree." },
  SOLOMON: { clue: "The king famed for wisdom who built the first temple in Jerusalem." },
  REHOBOAM: { clue: "Solomon's son whose harsh response helped split the united kingdom." },
  JEROBOAM: { clue: "The first ruler of the northern kingdom who established rival worship centers." },
  ELIJAH: { clue: "The prophet who confronted Baal's prophets on Mount Carmel and was taken up in a whirlwind." },
  ELISHA: { clue: "The prophet who succeeded Elijah and performed signs including healing a Syrian commander." },
  JEZEBEL: { clue: "The Phoenician queen who promoted Baal worship and opposed God's prophets." },
  HEZEKIAH: { clue: "A reforming king of Judah who prayed during an Assyrian siege and a severe illness." },
  JOSIAH: { clue: "The young king whose reforms followed the discovery of the Book of the Law." },
  MORDECAI: { clue: "The Jewish guardian who raised Esther and exposed a plot against the Persian king." },
  SHADRACH: { clue: "One of three exiles thrown into a blazing furnace for refusing idol worship." },
  MESHACH: { clue: "One of Daniel's three friends who survived Nebuchadnezzar's fiery furnace." },
  ABEDNEGO: { clue: "The Babylonian name of the third faithful exile delivered from the furnace." },
  ELIZABETH: { clue: "The elderly relative of Mary who became the mother of John the Baptist." },
  ZACHARIAS: { clue: "The priest struck unable to speak after doubting the angel's promise of a son." },
  MARY: { clue: "The young woman who accepted God's call to become the mother of Jesus." },
  JESUS: { clue: "The promised Messiah, Son of God, crucified and raised from the dead." },
  ANDREW: { clue: "The fisherman who followed Jesus and brought his brother Simon to meet him." },
  PHILIP: { clue: "The disciple who invited Nathanael to come and see Jesus." },
  BARTHOLOMEW: { clue: "One of the twelve apostles, traditionally identified with Nathanael." },
  THOMAS: { clue: "The disciple who wanted to see the risen Jesus' wounds before believing." },
  THADDAEUS: { clue: "One of the twelve apostles, also called Judas son of James." },
  SIMON: { clue: "The apostle distinguished from Peter by the title 'the Zealot.'" },
  JUDAS: { clue: "The disciple who betrayed Jesus with a kiss for thirty pieces of silver." },
  MATTHIAS: { clue: "The disciple chosen by lot to replace the betrayer among the Twelve." },
  MARTHA: { clue: "The Bethany woman who welcomed Jesus and confessed him as the Messiah." },
  LAZARUS: { clue: "The brother from Bethany whom Jesus called out of the tomb after four days." },
  NICODEMUS: { clue: "The Pharisee who visited Jesus at night and later helped prepare his body for burial." },
  ZACCHAEUS: { clue: "The short tax collector who climbed a tree to see Jesus pass through Jericho." },
  STEPHEN: { clue: "The church's first recorded martyr, known for wisdom and a vision of heaven." },
  PAUL: { clue: "The former persecutor transformed into an apostle to the Gentiles after meeting Christ on the road." },
  BARNABAS: { clue: "The encouraging believer who vouched for Paul and joined his first missionary journey." },
  SILAS: { clue: "Paul's missionary companion who sang hymns with him while imprisoned at Philippi." },
  LYDIA: { clue: "A seller of purple cloth whose household became the first recorded converts in Philippi." },
  PRISCILLA: { clue: "A tentmaker who served with her husband and helped instruct Apollos more accurately." },
  AQUILA: { clue: "The husband and ministry partner of Priscilla who worked alongside Paul." },
  APOLLOS: { clue: "An eloquent Alexandrian teacher who knew the Scriptures and was instructed by a ministry couple." },
  CORNELIUS: { clue: "A Roman centurion whose household received the gospel after Peter's vision." },
  DORCAS: { clue: "A Joppa disciple known for helping the poor whom Peter raised from death." },
  PHOEBE: { clue: "A trusted servant of the church at Cenchreae commended in Paul's letter to Rome." },
  ONESIMUS: { clue: "The runaway servant whom Paul sent back to be received as a beloved brother." },
  MELCHIZEDEK: { clue: "The mysterious king-priest of Salem who blessed Abraham." },
  NEBUCHADNEZZAR: { clue: "The Babylonian king who conquered Jerusalem and dreamed of a great statue." },
  MEPHIBOSHETH: { clue: "Jonathan's disabled son whom David welcomed to eat regularly at the king's table." },
  ZERUBBABEL: { clue: "The governor from David's line who helped lead the post-exile temple rebuilding." },

  // Bible places
  EDEN: { clue: "The garden home of the first man and woman before humanity's fall." },
  BABEL: { clue: "The plain where people built a tower and God confused their language." },
  CANAAN: { clue: "The land promised to Abraham's descendants and later entered by Israel." },
  EGYPT: { clue: "The nation where Joseph rose to power and Israel was later enslaved." },
  GOSHEN: { clue: "The fertile region where Joseph settled his family during the famine." },
  SINAI: { clue: "The wilderness mountain where Moses received God's covenant law." },
  MOAB: { clue: "The nation east of the Dead Sea from which Ruth came to Bethlehem." },
  EDOM: { clue: "The nation descended from Esau and located southeast of Judah." },
  ISRAEL: { clue: "The covenant nation named after Jacob's new name." },
  JUDAH: { clue: "The southern kingdom centered on Jerusalem and named for Jacob's fourth son." },
  JERUSALEM: { clue: "The city of David, site of the temple, crucifixion, and the church's Pentecost beginning." },
  BETHLEHEM: { clue: "David's hometown and the Judean village where Jesus was born." },
  NAZARETH: { clue: "The Galilean town where Jesus grew up." },
  GALILEE: { clue: "The northern region where Jesus conducted much of his public ministry." },
  SAMARIA: { clue: "The region between Judea and Galilee where Jesus spoke with a woman at a well." },
  JERICHO: { clue: "The walled city Israel circled before its defenses fell." },
  JORDAN: { clue: "The river Israel crossed into Canaan and where Jesus was baptized." },
  BETHEL: { clue: "The place where Jacob dreamed of a stairway reaching heaven." },
  HEBRON: { clue: "The ancient city near Abraham's burial cave that later became David's first royal capital." },
  BEERSHEBA: { clue: "A southern town associated with the patriarchs' wells and covenants." },
  DAMASCUS: { clue: "The Syrian city Paul was approaching when the risen Christ confronted him." },
  NINEVEH: { clue: "The Assyrian capital whose people repented after a reluctant prophet preached there." },
  BABYLON: { clue: "The empire and city that conquered Judah and carried many people into exile." },
  SODOM: { clue: "The wicked city destroyed alongside its neighboring city after Lot escaped." },
  GOMORRAH: { clue: "The city paired with Sodom as an example of divine judgment." },
  GETHSEMANE: { clue: "The garden where Jesus prayed in anguish and was arrested." },
  CALVARY: { clue: "A traditional name for the place outside Jerusalem where Jesus was crucified." },
  GOLGOTHA: { clue: "The Aramaic name meaning 'Place of the Skull,' where Jesus was crucified." },
  CAPERNAUM: { clue: "The lakeside Galilean town that became a center of Jesus' ministry." },
  BETHANY: { clue: "The village near Jerusalem where Martha, Mary, and Lazarus lived." },
  EMMAUS: { clue: "The village toward which two disciples walked when the risen Jesus joined them." },
  CANA: { clue: "The Galilean village where Jesus turned water into wine." },
  ANTIOCH: { clue: "The city where Jesus' followers were first called Christians and missionaries were commissioned." },
  EPHESUS: { clue: "The Asian city where Paul ministered extensively and opposition arose around Artemis worship." },
  CORINTH: { clue: "The Greek city whose divided church received two New Testament letters from Paul." },
  PHILIPPI: { clue: "The Macedonian city where Lydia believed and an earthquake opened a prison." },
  COLOSSE: { clue: "The city whose believers received Paul's letter emphasizing Christ's supremacy." },
  ROME: { clue: "The imperial capital Paul longed to visit and eventually reached as a prisoner." },
  CRETE: { clue: "The Mediterranean island where Titus was left to appoint church elders." },
  PATMOS: { clue: "The island where John received the visions recorded in the Bible's final book." },
  TARSHISH: { clue: "The distant destination a reluctant prophet chose while fleeing God's call." },
  SHILOH: { clue: "The early Israelite worship center where the tabernacle stood and Samuel served as a boy." },
  GILEAD: { clue: "A region east of the Jordan known for its healing balm." },
  JOPPA: { clue: "The port where Jonah boarded a ship and Peter later received a rooftop vision." },
  CAESAREA: { clue: "The coastal city where Peter preached to a Roman household and Paul was imprisoned." },
  SYCHAR: { clue: "The Samaritan town near Jacob's well where Jesus met a woman seeking water." },
  DECAPOLIS: { clue: "A region of ten cities where news spread after Jesus delivered a tormented man." },
  THESSALONICA: { clue: "The Macedonian city whose young church received letters about endurance and Christ's return." },
  MESOPOTAMIA: { clue: "The region between great rivers associated with Abraham's wider ancestral homeland." },
  ARARAT: { clue: "The mountainous region where the ark came to rest after the flood." },
  CARMEL: { clue: "The mountain where Elijah challenged the prophets of Baal." },
  ZION: { clue: "A biblical name for Jerusalem that also symbolizes God's dwelling and kingdom." },
  OLIVET: { clue: "The ridge east of Jerusalem associated with Jesus' teaching, prayer, and ascension." },

  // Bible themes
  AMEN: { clue: "A closing affirmation meaning 'truly' or 'let it be so.'" },
  ANGEL: { clue: "A heavenly messenger sent to deliver God's instructions or announcements." },
  ANOINT: { clue: "To set someone apart by applying oil, often for royal, priestly, or sacred service." },
  APOSTLE: { clue: "One who is specially sent out as an authorized witness and messenger." },
  BAPTISM: { clue: "The water sign of repentance, faith, and identification with Christ." },
  BLESSED: { clue: "A condition of receiving God's favor, flourishing, or gracious care." },
  BLESSING: { clue: "A gift, benefit, or spoken favor bestowed by God or invoked upon another." },
  CHURCH: { clue: "The gathered community of believers, described as Christ's body and bride." },
  COMMAND: { clue: "An authoritative instruction calling God's people to faithful obedience." },
  COMMANDMENTS: { clue: "God's covenant instructions, famously summarized in ten words given through Moses." },
  COVENANT: { clue: "A solemn binding relationship established through promises and commitments." },
  COURAGE: { clue: "Strength to act faithfully despite fear, danger, or opposition." },
  DELIVER: { clue: "To rescue someone from bondage, danger, enemies, or judgment." },
  DISCIPLE: { clue: "A learner and follower committed to the teaching and way of a master." },
  FAITH: { clue: "Trusting confidence in God and what he has promised, even when unseen." },
  FASTING: { clue: "Temporarily abstaining from food to seek God with focused prayer and humility." },
  FORGIVE: { clue: "To release a debt or offense instead of holding it against someone." },
  GLORY: { clue: "The radiant weight, honor, and majesty belonging to God." },
  GOSPEL: { clue: "The good news of God's saving work through Jesus Christ." },
  GRACE: { clue: "God's undeserved favor and empowering generosity toward people." },
  HEAVEN: { clue: "God's dwelling realm and the believer's promised home in his presence." },
  HOLINESS: { clue: "The quality of being set apart from sin and devoted to God." },
  HOLY: { clue: "Set apart, morally pure, and uniquely belonging to God." },
  HOPE: { clue: "Confident expectation rooted in God's character and future promises." },
  HUMBLE: { clue: "To reject self-importance and depend upon God while serving others." },
  JUSTICE: { clue: "Doing what is right and fair, especially defending those who are vulnerable." },
  KINDNESS: { clue: "Compassionate goodness expressed through generous words and actions." },
  KINGDOM: { clue: "God's sovereign reign, announced by Jesus as drawing near." },
  LIGHT: { clue: "A biblical image for God's truth, purity, guidance, and life." },
  LOVE: { clue: "Self-giving devotion identified as the greatest command and defining Christian virtue." },
  MERCY: { clue: "Compassion that withholds deserved judgment and responds to need." },
  MIRACLE: { clue: "An extraordinary sign of divine power that reveals God's activity and authority." },
  PARDON: { clue: "Release from guilt or punishment after an offense." },
  PARABLE: { clue: "A memorable story or comparison used to reveal spiritual truth." },
  PEACE: { clue: "Wholeness and reconciliation with God and others, deeper than the absence of conflict." },
  PRAISE: { clue: "Joyfully declaring God's character, greatness, and mighty acts." },
  PRAYER: { clue: "Speaking and listening to God through worship, confession, thanks, and request." },
  PROMISE: { clue: "A trustworthy commitment that gives confidence in what God will do." },
  PROPHET: { clue: "A person called to communicate God's message faithfully to others." },
  REDEEM: { clue: "To rescue or buy back from bondage, loss, or debt." },
  REDEMPTION: { clue: "Freedom secured through the payment of a price, fulfilled in Christ." },
  REPENTANCE: { clue: "A sincere turning away from sin and back toward God." },
  RESURRECTION: { clue: "Rising bodily from death, central to the Christian proclamation about Jesus." },
  RIGHTEOUSNESS: { clue: "Right standing and right living according to God's character and will." },
  SABBATH: { clue: "A regular day of rest and worship established in the creation and covenant rhythms." },
  SALVATION: { clue: "God's rescue from sin, death, and judgment into restored life with him." },
  SAVIOR: { clue: "A rescuer who delivers people from danger, bondage, or sin." },
  SCRIPTURE: { clue: "The sacred writings received as God's written word." },
  SERMON: { clue: "An address that explains and applies spiritual truth to its hearers." },
  SERVANT: { clue: "One who willingly works for another, a role Jesus modeled for his followers." },
  SPIRIT: { clue: "The divine Helper who empowers, guides, convicts, and lives within believers." },
  TRINITY: { clue: "The Christian name for one God eternally known as Father, Son, and Holy Spirit." },
  TRUTH: { clue: "What accords with God's reality, character, and trustworthy revelation." },
  VICTORY: { clue: "Triumph over enemies, sin, and death through God's power." },
  WISDOM: { clue: "Skill in living rightly by applying God's truth with reverence and discernment." },
  WITNESS: { clue: "One who truthfully testifies to what has been seen, heard, or experienced." },
  WORSHIP: { clue: "The wholehearted response of reverence, love, obedience, and praise offered to God." },
  CREATION: { clue: "God's act of bringing the heavens, earth, and living things into being." },
  FLOOD: { clue: "The great judgment survived by one family inside an ark." },
  PASSOVER: { clue: "The feast remembering Israel's deliverance when judgment passed over marked homes." },
  PENTECOST: { clue: "The feast day when the Holy Spirit came upon the gathered disciples with power." },
  TRANSFIGURATION: { clue: "The mountaintop event when Jesus' appearance shone and Moses and Elijah appeared." },
  CRUCIFIXION: { clue: "Execution on a cross, the manner in which Jesus gave his life." },
  DISCIPLESHIP: { clue: "The lifelong process of following Jesus, learning his way, and becoming like him." },
  PERSECUTION: { clue: "Hostility or suffering endured because of faithfulness to God." },
  RECONCILIATION: { clue: "The restoration of a broken relationship, especially between humanity and God." },
  PROVIDENCE: { clue: "God's wise, purposeful care and governance over creation and circumstances." },
  SACRIFICE: { clue: "An offering given at a cost, ultimately exemplified by Christ giving himself." },
  OFFERING: { clue: "A gift presented to God as an act of worship, gratitude, or dedication." },
  SHEPHERD: { clue: "A caretaker of sheep and a biblical picture of God's guidance and leadership." },
  VINEYARD: { clue: "A cultivated place for grapes, often used as a picture of God's people." },
  MUSTARD: { clue: "A tiny seed Jesus used to picture faith and the surprising growth of God's kingdom." },
  LEAVEN: { clue: "A small fermenting agent Jesus used to picture quiet influence spreading through everything." },
  TALENT: { clue: "A large unit of money in Jesus' story about servants entrusted with their master's wealth." },
  WIDOW: { clue: "A woman whose husband has died, repeatedly named among those God's people must protect." },
  ORPHAN: { clue: "A child without parental protection, often paired with the widow in calls for justice." },
  PRIEST: { clue: "A person appointed to serve in worship and represent the people before God." },
  LEVITE: { clue: "A member of Levi's tribe set apart for duties connected with Israel's worship." },
  PHARISEE: { clue: "A member of a Jewish movement known for strict attention to law and tradition." },
  SADDUCEE: { clue: "A priestly Jewish group that denied the resurrection and accepted a narrower scriptural authority." },

  // Bible objects
  ALTAR: { clue: "A raised place where sacrifices, incense, or memorial offerings were presented to God." },
  BIBLE: { clue: "The collection of sacred writings forming the Christian Scriptures." },
  CROSS: { clue: "The Roman instrument of execution that became the central symbol of Christ's sacrificial death." },
  MANNA: { clue: "The bread-like food God provided each morning for Israel in the wilderness." },
  TABERNACLE: { clue: "Israel's portable sanctuary built in the wilderness according to God's pattern." },
  TEMPLE: { clue: "The permanent sanctuary in Jerusalem built as the center of Israel's worship." },
  INCENSE: { clue: "A fragrant substance burned in worship, symbolically associated with prayer." },
  CENSER: { clue: "A vessel used by priests to carry burning coals and fragrant incense." },
  LAMPSTAND: { clue: "The seven-branched light fixture placed in the holy place of Israel's sanctuary." },
  SCROLL: { clue: "A rolled writing surface on which biblical texts, messages, and records were written." },
  TABLETS: { clue: "The stone slabs on which the covenant commandments were inscribed." },
  CROWN: { clue: "A royal headpiece and biblical symbol of authority, honor, or victorious reward." },
  SCEPTER: { clue: "A staff held by a ruler as a symbol of royal authority." },
  SLING: { clue: "The simple shepherd's weapon David used against a Philistine giant." },
  STONE: { clue: "The small projectile chosen from a stream that brought down Goliath." },
  STAFF: { clue: "A walking and shepherding rod associated especially with Moses and divine guidance." },
  TUNIC: { clue: "A basic garment, including the special robe Jacob gave his favored son." },
  ROBE: { clue: "A long garment that could signify office, honor, mourning, or royal dignity." },
  SANDALS: { clue: "Footwear removed on holy ground and shaken free as a sign against rejection." },
  CHARIOT: { clue: "A horse-drawn vehicle used for war, royal travel, and a dramatic desert encounter in Acts." },
  TRUMPET: { clue: "A wind instrument used to summon Israel, announce feasts, warn of danger, and celebrate." },
  HARP: { clue: "A stringed instrument associated with David's music and Israel's worship." },
  LYRE: { clue: "A small stringed instrument frequently used to accompany biblical songs of praise." },
  SYNAGOGUE: { clue: "A local Jewish gathering place for prayer, Scripture reading, and teaching." },
  SANCTUARY: { clue: "A holy place set apart for God's presence and worship." },
  DENARIUS: { clue: "A Roman silver coin often representing an ordinary laborer's daily wage." },
  FRANKINCENSE: { clue: "A fragrant resin given by eastern visitors to the child Jesus and used in worship." },
  MYRRH: { clue: "An aromatic resin associated with costly gifts, anointing, suffering, and burial." },
  BREASTPLATE: { clue: "A high-priestly garment bearing Israel's tribes, also used as an image of spiritual armor." },
  EPHOD: { clue: "A sacred priestly garment worn especially by Israel's high priest." },
  PITCHER: { clue: "A clay water vessel, like those broken to reveal the torches of Gideon's army." },
  BASKET: { clue: "A woven container used for food, offerings, and the infant Moses' river rescue." },
  NETS: { clue: "Fishing equipment Jesus told several disciples to leave when calling them to follow." },
  LOAVES: { clue: "Bread portions multiplied by Jesus to feed a vast crowd." },
  SWORD: { clue: "A bladed weapon also used as a picture of God's penetrating word." },
  SHIELD: { clue: "Protective battle equipment used as a biblical image for God and for faith." },
  HELMET: { clue: "Protective headgear used in the New Testament picture of spiritual armor." },
  SCROLLS: { clue: "Rolled written documents Paul asked Timothy to bring, especially the parchments." },
  VINE: { clue: "A climbing plant Jesus used when teaching that his followers must remain connected to him." },
  FIGTREE: { clue: "A fruit tree used in prophetic imagery and once addressed by Jesus for bearing no fruit." },
  WELL: { clue: "A deep water source central to several meetings, including Jesus' conversation in Samaria." },
  DOVE: { clue: "A bird sent from the ark and later seen as the Spirit descended at Jesus' baptism." },
  LAMB: { clue: "A young sheep used in sacrifice and a title pointing to Jesus as God's sin-bearer." },
  OXEN: { clue: "Strong cattle used for plowing and sacrifice, protected by a law against muzzling while working." },
};

export function getBibleWordHint(answer: string) {
  return BIBLE_WORD_HINTS[answer.toUpperCase()];
}
